name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install bats
      run: sudo npm install -g bats
    - name: init
      run: mkdir -p build && pushd build && cmake .. && popd
    - name: compile
      run: ./compile.sh
  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: install bats
      run: brew unlink bats && brew install bats-core
    - name: init
      run: mkdir -p build && pushd build && cmake .. && popd
    - name: compile
      run: ./compile.sh
